# Generated by Django 5.2.7 on 2025-11-08 08:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardErrorResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=False)),
                ('error_code', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('error_extra', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField()),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='StandardResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ok', models.BooleanField(default=True)),
                ('message', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField()),
                ('request_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
