# Generated by Django 5.2.5 on 2025-11-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soho_core_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='standarderrorresponsemodel',
            table='StandardResponseError',
        ),
        migrations.AlterModelTable(
            name='standardresponsemodel',
            table='StandardResponse',
        ),
    ]
