# soho_core_api/pylibs/snmp.py
from __future__ import annotations
import os
import re
import json
from datetime import datetime
from typing import Dict, Any, List, Optional, Union
from pylibs import logger, CLICommandError, run_cli_command


class SNMPManager:
    """
    مدیریت کامل سرویس SNMP.
    تمام توابع فقط داده خام (Dict, List, str, None) یا استثنا برمی‌گردانند.
    """
    SNMPD_CONFIG_PATH = "/etc/snmp/snmpd.conf"
    SNMP_CONFIG_PATH = "/etc/snmp/snmp.conf"

    def __init__(self) -> None:
        pass

    def get_snmp_config(self) -> Dict[str, Any]:
        """
        دریافت تنظیمات فعلی SNMP از فایل پیکربندی.

        Returns:
            Dict حاوی تنظیمات فعلی SNMP.
        """
        config = {
            "communities": [],
            "contact": "",
            "location": "",
            "sys_name": "",
            "enabled": False,
            "port": "161",
            "version": "2c"
        }
        
        try:
            if os.path.exists(self.SNMPD_CONFIG_PATH):
                with open(self.SNMPD_CONFIG_PATH, "r", encoding="utf-8") as f:
                    content = f.read()
                
                # استخراج جامعیت‌ها
                community_pattern = r'rocommunity\s+([^\s]+)(?:\s+([^\s]+))?'  # مثال: rocommunity public localhost
                communities = re.findall(community_pattern, content)
                config["communities"] = [comm[0] for comm in communities]  # فقط نام جامعیت
                
                # استخراج اطلاعات سیستم
                contact_match = re.search(r'sysContact\s+(.+)', content)
                if contact_match:
                    config["contact"] = contact_match.group(1).strip()
                
                location_match = re.search(r'sysLocation\s+(.+)', content)
                if location_match:
                    config["location"] = location_match.group(1).strip()
                
                name_match = re.search(r'sysName\s+(.+)', content)
                if name_match:
                    config["sys_name"] = name_match.group(1).strip()
                
                # استخراج پورت
                port_match = re.search(r'agentAddress\s+.*:(\d+)', content)
                if port_match:
                    config["port"] = port_match.group(1)
                
                # بررسی وضعیت سرویس
                from pylibs.service import ServiceManager
                service_manager = ServiceManager()
                config["enabled"] = service_manager.is_active("snmpd")
                
        except (IOError, OSError) as e:
            logger.error(f"خطا در خواندن فایل پیکربندی SNMP: {e}")
            raise CLICommandError(f"خطا در خواندن فایل پیکربندی SNMP: {e}")
        
        return config

    def get_snmp_status(self) -> Dict[str, Any]:
        """
        دریافت وضعیت فعلی سرویس SNMP.

        Returns:
            Dict حاوی وضعیت سرویس SNMP.
        """
        from pylibs.service import ServiceManager
        service_manager = ServiceManager()
        
        status = service_manager.get_status("snmpd")
        
        return {
            "service_name": "snmpd",
            "active_state": status["active_state"],
            "load_state": status["load_state"],
            "sub_state": status["sub_state"],
            "main_pid": status["main_pid"],
            "enabled": status["enabled"],
            "running": status["active_state"] == "active"
        }

    def set_snmp_config(self, community: str, contact: Optional[str] = None, 
                       location: Optional[str] = None, sys_name: Optional[str] = None,
                       port: str = "161", version: str = "2c") -> None:
        """
        تنظیم پیکربندی SNMP در فایل snmpd.conf.

        Args:
            community: نام جامعیت SNMP
            contact: اطلاعات تماس سیستم (اختیاری)
            location: مکان سیستم (اختیاری)
            sys_name: نام سیستم (اختیاری)
            port: پورت SNMP (پیش‌فرض 161)
            version: نسخه SNMP (پیش‌فرض 2c)
        """
        config_content = f"""# Generated by SOHO Core API
agentAddress  udp:{port}
rocommunity {community}  default    -V all
#rwcommunity {community} default    -V all

# System Information
sysLocation    {location if location else 'Unknown Location'}
sysContact     {contact if contact else 'Unknown Contact'}
sysName        {sys_name if sys_name else 'SOHO SNMP Server'}
sysServices    72

# Access Control
com2sec notConfigUser  default       {community}
group   notConfigGroup v1           notConfigUser
group   notConfigGroup v2c           notConfigUser
view    systemview    included   .1.3.6.1.2.1.1
view    systemview    included   .1.3.6.1.2.1.25.1.1
access  notConfigGroup ""      any       noauth    exact  systemview none none
dontLogTCPWrappersConnects yes
"""

        try:
            # ایجاد دایرکتوری اگر وجود نداشته باشد
            os.makedirs(os.path.dirname(self.SNMPD_CONFIG_PATH), exist_ok=True)
            
            # نوشتن فایل پیکربندی
            with open(self.SNMPD_CONFIG_PATH, "w", encoding="utf-8") as f:
                f.write(config_content)
            
            # ریلود سرویس SNMP
            self._reload_snmp_service()
            
        except (IOError, OSError) as e:
            logger.error(f"خطا در نوشتن فایل پیکربندی SNMP: {e}")
            raise CLICommandError(f"خطا در نوشتن فایل پیکربندی SNMP: {e}")

    def start_snmp_service(self) -> None:
        """شروع سرویس SNMP."""
        from pylibs.service import ServiceManager
        service_manager = ServiceManager()
        service_manager.start("snmpd")

    def stop_snmp_service(self) -> None:
        """توقف سرویس SNMP."""
        from pylibs.service import ServiceManager
        service_manager = ServiceManager()
        service_manager.stop("snmpd")

    def restart_snmp_service(self) -> None:
        """ریستارت سرویس SNMP."""
        from pylibs.service import ServiceManager
        service_manager = ServiceManager()
        service_manager.restart("snmpd")

    def enable_snmp_service(self) -> None:
        """فعال‌سازی سرویس SNMP در بوت سیستم."""
        from pylibs.service import ServiceManager
        service_manager = ServiceManager()
        service_manager.enable("snmpd")

    def disable_snmp_service(self) -> None:
        """غیرفعال‌سازی سرویس SNMP در بوت سیستم."""
        from pylibs.service import ServiceManager
        service_manager = ServiceManager()
        service_manager.disable("snmpd")

    def test_snmp_connection(self, community: str = "public", version: str = "2c", 
                           host: str = "localhost", port: str = "161") -> bool:
        """
        تست اتصال به سرویس SNMP.

        Args:
            community: نام جامعیت SNMP
            version: نسخه SNMP
            host: هاست SNMP
            port: پورت SNMP

        Returns:
            bool: True اگر اتصال موفق باشد
        """
        try:
            cmd = ["/usr/bin/snmpwalk", "-v", version, "-c", community, f"{host}:{port}", "system"]
            stdout, stderr = run_cli_command(cmd, use_sudo=True)
            return len(stdout.strip()) > 0
        except CLICommandError:
            return False

    def _reload_snmp_service(self) -> None:
        """ریلود سرویس SNMP برای اعمال تغییرات."""
        try:
            run_cli_command(["/usr/bin/sudo", "/usr/sbin/service", "snmpd", "reload"], use_sudo=False)
        except CLICommandError:
            run_cli_command(["/usr/bin/sudo", "/bin/systemctl", "reload", "snmpd"], use_sudo=False)